config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :employees
  
  # API
  namespace :api do
    post "orders", to: "orders#create"
    post "login", to: "auth#index"
    get "restaurants", to: "restaurants#index"
    get "products", to: "products#index"
    get "orders", to: "orders#index"
    get "order/:type/:id", to: "orders#index"
    post "order/:id/status", to: "orders#set_status"
    
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  belongs_to :address
  validates :user_id, :address_id, :phone, presence: true
  validates_uniqueness_of :user_id
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.all  
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
        redirect_to employees_path, notice: "Employee was successfully created."
    else
        render :new
    end
  end

  def new
    @employee = Employee.new
  end

  private

  def employee_params
    params.require(:employee).permit(:phone, :email, :user_id, :address_id)
  end
end

app/views/employees/index.html.erb
<h1>Employees</h1>

<%= link_to "New employee", new_employee_path, class: "btn btn-primary" %>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.user.name %></td>
        <td><%= employee.address.street_address %>, <%= employee.address.city %>, <%= employee.address.postal_code %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= form_with model: @employee, url: employees_path, class: "form-horizontal" do |form| %>
  <div class="form-group">
    <%= form.label :user_id, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.collection_select :user_id, User.all, :id, :name, {}, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :address_id, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.collection_select :address_id, Address.all, :id, :full_address, {}, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :phone, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_field :phone, required: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :email, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.email_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit "Create", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>