config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :employees
  
  # API
  namespace :api do
    post "orders", to: "orders#create"
    post "login", to: "auth#index"
    get "restaurants", to: "restaurants#index"
    get "products", to: "products#index"
    get "orders", to: "orders#index"
    get "order/:type/:id", to: "orders#index"
    post "order/:id/status", to: "orders#set_status"
    
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">RFD Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>

        <li class="nav-item">
          <!-- Since Rails 7 uses Turbo instead of Webpacker, we use turbo_method inside a data parameter instead of method: :delete (< Rails 7) -->
          <%= link_to "Sign out", destroy_user_session_path, class: 'nav-link', data: { turbo_method: :delete } %> 
        </li>

        <li class="nav-item">
          <%= link_to 'Employees', employees_path, class: 'nav-link' %>
        </li>

      <% else %>

        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>

      <% end %>
      </ul>
    </div>
  </div>
</nav>